In [68]:
import numpy as np

In [69]:
#Print the numpy version and the configuration

print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/anaconda\\Library\\include']


In [70]:
#Create a null vector of size 10

a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
#How to find the memory size of any array

z= np.zeros((10,10))
print("%d bytes" %(z.size*z.itemsize))

800 bytes


In [72]:
#  Create a null vector of size 10 but the fifth value which is 1
z =np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [73]:
#Create a vector with values ranging from 10 to 49

a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [74]:
#Reverse a vector (first element becomes last)

a = a[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [75]:
# Create a 3x3 matrix with values ranging from 0 to 8

a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
#Find indices of non-zero elements from [1,2,0,0,4,0] 
a = [1,2,0,0,4,0] 
nz =np.nonzero(a)
print(nz)

(array([0, 1, 4], dtype=int64),)


In [77]:
#Create a 3x3 identity matrix

a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
#Create a 3x3x3 array with random values 

a = np.random.random((3,3,3))
print(a)

[[[0.86559324 0.4309363  0.39669067]
  [0.22984886 0.42800869 0.69859882]
  [0.3757688  0.98397437 0.90107181]]

 [[0.81990339 0.22875173 0.17076761]
  [0.18093172 0.12069124 0.45526449]
  [0.58116352 0.50452791 0.07067939]]

 [[0.28294693 0.84266992 0.35473044]
  [0.97271737 0.94057739 0.31297583]
  [0.39080724 0.9610085  0.3924792 ]]]


In [79]:
#Create a 10x10 array with random values and find the minimum and maximum values

a = np.random.random((10,10))
a


array([[0.49922243, 0.08613872, 0.73566971, 0.58372428, 0.67915783,
        0.29776633, 0.72659641, 0.31568165, 0.96783009, 0.67751902],
       [0.48586685, 0.48380863, 0.80473322, 0.5757669 , 0.05103068,
        0.87885096, 0.34239132, 0.63741238, 0.77150916, 0.95880334],
       [0.67826482, 0.36679913, 0.1418555 , 0.25745382, 0.58720328,
        0.67749824, 0.24370389, 0.12046112, 0.92486833, 0.51216566],
       [0.93101078, 0.65425884, 0.20943541, 0.46318946, 0.38225319,
        0.22346603, 0.57201757, 0.66238746, 0.75158924, 0.65847866],
       [0.48992183, 0.74629391, 0.46066357, 0.69685504, 0.88294272,
        0.57730629, 0.14994695, 0.23980027, 0.27888212, 0.21363823],
       [0.02094883, 0.59169496, 0.21454872, 0.97140895, 0.85591169,
        0.83434405, 0.11443143, 0.0173785 , 0.68570638, 0.79523087],
       [0.05910948, 0.64192708, 0.15408075, 0.17503937, 0.18309967,
        0.4527058 , 0.68135408, 0.20581047, 0.50492428, 0.77718669],
       [0.92919795, 0.1013103 , 0.4438368

In [80]:
a.min()

0.0173785000030362

In [81]:
a.max()

0.9860168149060737

In [82]:
#Create a random vector of size 30 and find the mean value

b = np.random.random(30)
b

array([0.29052427, 0.79533738, 0.49570227, 0.18967513, 0.86028551,
       0.16252425, 0.82684799, 0.60620998, 0.87106806, 0.1988237 ,
       0.83785831, 0.5348938 , 0.46618355, 0.19558265, 0.70297428,
       0.8920078 , 0.26273207, 0.33987708, 0.0049939 , 0.10678751,
       0.8730004 , 0.25647434, 0.58231998, 0.779347  , 0.46700428,
       0.13713353, 0.59954777, 0.08838666, 0.73278653, 0.06436776])

In [83]:
np.mean(b)

0.47404192509575616

In [84]:
# Create a 2d array with 1 on the border and 0 inside

a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [85]:
#How to add a border (filled with 0's) around an existing array?

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [86]:
#What is the result of the following expression?

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [87]:
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [88]:
#Create a 5x5 matrix with values 1,2,3,4 just below the diagona

a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [89]:
#Create a 8x8 matrix and fill it with a checkerboard pattern

a = np.zeros((8,8),dtype = int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [90]:
#Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [91]:
#21. Create a checkerboard 8x8 matrix using the tile function

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [92]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

z =np.dot(np.ones((5,3)),np.ones((3,2)))
print(z)


[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [93]:
#Given a 1D array, negate all elements which are between 3 and 8, in place

z = np.arange(8)
z[(3<3)&(z<8)]*=-1
print(z)

[0 1 2 3 4 5 6 7]


In [94]:
#How to get all the dates corresponding to the month of July 2016?

a= np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [95]:
 #35. How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)    

array([-1.5, -1.5, -1.5])

In [96]:
#36. Extract the integer part of a random array of positive numbers using 4 different methods

Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))


[4. 9. 8. 8. 2. 6. 9. 0. 4. 4.]
[4. 9. 8. 8. 2. 6. 9. 0. 4. 4.]
[4. 9. 8. 8. 2. 6. 9. 0. 4. 4.]
[4 9 8 8 2 6 9 0 4 4]
[4. 9. 8. 8. 2. 6. 9. 0. 4. 4.]


In [97]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4

b = np.zeros((5,5))
b += np.arange(5)
print(b)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [98]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [99]:
#40. Create a random vector of size 10 and sort it 
a = np.random.random(10)
a.sort()
print(a)

[0.08050978 0.16549106 0.40698005 0.4187683  0.63312459 0.71109158
 0.79249644 0.80443421 0.85889083 0.93278106]


In [100]:
#41. How to sum a small array faster than np.sum? 

z = np.arange(10)
np.add.reduce(z)

45

In [101]:
#42. Consider two random array A and B, check if they are equal

a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

equal = np.allclose(a,b)
print('equal')

equal


In [102]:
#45. Create random vector of size 10 and replace the maximum value by 0

a = np.random.random(10)
a[a.argmax()]=0
print(a)

[0.29164422 0.00395633 0.10912886 0.14944447 0.05004517 0.54374072
 0.         0.40399719 0.52830191 0.1657036 ]


In [103]:
#53. How to convert a float (32 bits) array into an integer (32 bits) 

e = np.random.rand(10)*100.astype(np.float32)
Y = e.view(np.int32)
Y[:] = Z
print(Y)

SyntaxError: invalid syntax (<ipython-input-103-52181a59243e>, line 3)

In [105]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24566572  0.12252964]


In [106]:
##### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.03363016, 0.24781419, 0.07542059, 0.74943684, 0.05536269,
        0.8164543 , 0.95945308, 0.741186  , 0.57113361, 0.39395702],
       [0.00706361, 0.0520504 , 0.01584119, 0.15741024, 0.01162827,
        0.17148645, 0.20152163, 0.15567725, 0.11995978, 0.08274596],
       [0.00522819, 0.03852557, 0.011725  , 0.11650858, 0.00860677,
        0.12692721, 0.14915801, 0.11522589, 0.08878929, 0.06124515],
       [0.00992359, 0.073125  , 0.0222551 , 0.22114379, 0.01633642,
        0.24091929, 0.28311537, 0.21870913, 0.16853008, 0.11624882],
       [0.02906456, 0.21417122, 0.06518158, 0.64769415, 0.04784671,
        0.70561339, 0.82919882, 0.64056342, 0.49359715, 0.34047386],
       [0.0050134 , 0.03694281, 0.0112433 , 0.11172203, 0.00825317,
        0.12171264, 0.14303013, 0.11049204, 0.08514154, 0.058729  ],
       [0.02533934, 0.18672077, 0.05682722, 0.56467882, 0.04171417,
        0.61517451, 0.72291993, 0.55846204, 0.43033252, 0.29683513],
       [0.01912583, 0.14093455, 0.0428924

In [107]:
##### 96. Given a two dimensional array, how to extract unique rows? (★★★)

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [108]:
#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 3]
 [2 4 2]
 [3 2 2]
 [4 1 3]
 [4 3 3]
 [3 4 3]
 [4 3 0]
 [1 1 2]
 [3 0 2]
 [0 3 0]]
[[2 0 3]
 [2 4 2]
 [3 2 2]
 [4 1 3]
 [4 3 3]
 [3 4 3]
 [4 3 0]
 [1 1 2]
 [3 0 2]
 [0 3 0]]
[[2 0 3]
 [2 4 2]
 [3 2 2]
 [4 1 3]
 [4 3 3]
 [3 4 3]
 [4 3 0]
 [1 1 2]
 [3 0 2]
 [0 3 0]]
